### ISSUE TITLE
Turn off toast notification for fetching time of contacts

### ISSUE THREAD

**Issue by NIkhilbadveli** [deepakkumardk/KontactPicker#3]
So, is there any parameter for turning off the toast notification that says "Fetching time 80ms", something like that?

**Comment by deepakkumardk** [comment]
You could use the **_debugMode_** property in the **KontactPicerItem** 

`
 val item = KontactPickerItem().apply {
        debugMode = BuilldConfig.DEBUG
        //other properties
    }
`

For more see [here](https://github.com/deepakkumardk/KontactPicker#customization)
